# THYMELEAF (ThymeleafAutoConfiguration)
# 开启模板缓存（默认值： true ）
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6678
    # 密码，没有则留空或注释掉此项
    password: 234wer@#$WER
    timeout: 10000ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（负值为没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（负值为没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  thymeleaf:
    cache: true
# 检查模板是否存在，然后再呈现
    check-template: true
# 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
#Content-Type 的值（默认值： text/html ）
    content-type: text/html
# 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
# 模板编码
    encoding: UTF-8
# 要被排除在解析之外的视图名称列表，⽤逗号分隔
    excluded-view-names:
# 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML5
# 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
# 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
# 应用服务 WEB 访问端口
server:
  port: 8080